### ISSUE TITLE
Update to run with notebook 4.2

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Platform/nb_conda_kernels#18]
> Do not merge until notebook 4.2 is released.

Use the new canonical API from https://github.com/jupyter/notebook/pull/879

- [ ] update `__int__.py` with new structure
- [ ] remove internal `nbextension` structure
- [ ] update `conda.recipe`
  - [ ] `meta.yml`
  - [ ] `(post|pre)-(un)link.(bat|sh)`

## 
- [ ] investigate whether the kernel manager can be hot-swapped

Unlike some of the [other](https://github.com/Anaconda-Server/nb_anacondacloud/pull/19) [extensions](https://github.com/Anaconda-Server/nbpresent/pull/61), `nb_conda_kernels` might not be able to be a "pure" server extension, as it needs something changed in the configuration outside of the (new) `nbserver_extensions` key, namely [`kernel_spec_manager_class`](https://github.com/Anaconda-Server/nb_conda_kernels/blob/master/nb_conda_kernels/install.py#L42) which will already have been [loaded](https://github.com/jupyter/notebook/blob/3feea618027713a53e540b6f7eb1e3abef57dc03/notebook/notebookapp.py#L1118) by the time the server extension hits.

An issue was created to allow general enable-time configuration:
https://github.com/jupyter/notebook/issues/1196

With an eye towards keeping scope creep down, this will likely _not_ land in `notebook` 4.2, unless we advocate strongly for it, and do the work... but since we don't _really_ care how many commands a user has to run (i mean, `conda install`), this wouldn't buy us much.

> this is pretty off-topic. sorry

## :handbag:-o-files
A proposed long-term approach (5.0) is to adopt a bag-of-files approach for configuration. This would be _great_ for us, as it would make it very easy to put extensions into Anaconda, would remove the need for post-link/pre-unlink scripts, etc. as we'd just have to create a unique (built!) JSON file (per package) in a predictable location which would be automatically read on Jupyter app launch.

Right now, the jupyter apps look in the `$CONF` paths (or the equivalent win paths):
- `~.jupyter`
- `${PREFIX}/etc/jupyter`
- `/usr/local/etc/jupyter`
- `/etc/jupyter`
- some command line thing

for:
- `jupyter_notebook_config.json`
- `nbconfig/`
  - `tree.json`
  - `notebook.json`
  - `common.json`
  - `terminal.json`
  - `editor.json`
- other stuff

All these will likely be maintained for backwards-compatibility's sake, as they are countable, and a good place to put different _user_ config choices. In addition, a new folder (say, `conf.d`) in each `$CONF` path would contain, for example, `nbconfig/conf.d/nb_conda_kernels.json`.

Inside of this would be either a `pure` config object:
```yaml
{"NotebookApp" : {
  "nbserver_extensions": {"nb_conda_kernels": true},
  "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager"},
}
```

...or a wrapped one, to provide metadata suitable to drive an (unconfigurable!) GUI, introspection, etc...

```yaml
{
  "version": "0.1.0",
  "name": "nb_conda_kernels",
  "title": "Conda Kernels",
  "description": "Use R, Python and other languages from local conda environments as Jupyter kernels",
  "autoenable": true,
  "...": ..., # other things i haven't imagined
  "config": ..., #the thing from above
}
```

These would **certainly** be schema constrained.

Some issues arise, such as in what order to load the config (or thought differently, precedence).  What if `nb_conda_kernels` is fighting something else for `kernel_spec_manager_class`? Who wins?

The proven approach from, say, [apache httpd](https://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-apache-config.html) is to use natural ordering, i.e. `001_nb_conda_kernels.json`. This could also be hidden inside the config wrapper... probably better.

Whoever is "better" (let's say, larger) wins.

In addition, in a wrapper one could include a validation step: perhaps using the JSON Patch `test` op, a JSON schema, or some home-rolled validation. This would amount to duplicating the config, probably, but would be a declarative, data-driven way to ensure the health of the system. Basically, one could say "if `nb_conda_kernels` is enabled, then `kernel_spec_manager_class` must be CondaKernelSpecManager".

Other approaches could involve JSON Patch or JSON-LD.
